### PR TITLE
Made script work; added --saveas 

### PR DESCRIPTION
**Pull request by sector-f**
Got the script to work by changing `convert $file2` to `convert $file`, which hopefully didn't break anything
Also added --saveas to allow the user to save wherever they want (default is still filename-polyfy).

### CODE REVIEW

**Comment by onespaceman** [comment]
I already pushed an update earlier today that should have fixed the same issue.
Also made polyfy not overwrite files any more, but I'll add in the save as this evening.

**Comment by sector-f** [comment]
Yeah, you're right. My bad. I didn't notice that you changed the default invert to none.
Eh, at least --saveas is useful :P

**Comment by sector-f** [comment]
If you want, I could close this pull request, re-sync my fork with yours, and just reimplement --saveas. Shouldn't be too difficult.

**Comment by onespaceman** [comment]
yeah. go for it.
Also, see if my changes actually fixed the problem.

**Pull request closed without merging**
