### PR TITLE
Rewrote script for readability and consistency.

### PR DESCRIPTION
**Pull request by muse**
I've been enjoying your scripts functionality, but the code itself was quite bothersome. 
- The variable names were a little... off?
- Inconsistency regarding the file arguments.
- There are really long lines regarding the `convert` section at the bottom.
- Not really any clear form of `--help` or usage.
- There's inconsistency regarding `[` and `[[`.
- Variables that were existent but not modifiable.

I've tried to rewrite most of the miscellaneous parts of the script and tried formatting the code a little better. There's now a detailed `--help` section available covering all the available flags and the _synopsis_. I've made the `border color` variable available for change, since it was defined but you couldn't change it. I changed all the `[` to `[[` and decided on  a single consistent way of calling if statements. The arguments are now handled through `getopt`. And last but not least, the lines at the bottom converting the image are now more readable.

Just throwing it out there, there's always the chance I oversaw one of the mentioned issues as well.

### CODE REVIEW

**Comment by neeasade** [comment]
+1

**Comment by sector-f** [comment]
+1

**Comment by onespaceman** [comment]
Ok. I'm awake.

I have a few questions/comments about the changes. I've only been teaching myself scripting for the past few weeks so bear with me.

Could you explain the Getopts part?  I see the command assigned to $OPTION, but can't figure out what it does past that.

Why replace rgb with just long names? I would think a --negate flag would be faster to type out.

The table for the default rotation values isn't necessary, since it part of initially drawing the shapes and they don't affect the behavior of rotation.

Some of the help descriptions are long winded for my taste :P

Otherwise, I like it.  Thanks for taking the time to help me out.

**Comment by muse** [comment]
I thought you may have died, I am glad to help you explain it a little better. I was rather tired at the time of writing and now observe myself missing a critical part of the getopt. Right below the `OPTION=` there should be `eval set -- "$OPTIONS"`. I will add that ASAP. I hope that makes it a little more clear. Otherwise http://stackoverflow.com/a/7948533/3170442 should help you understand it a little better. 

Getopt relies on prefixing long arguments (`--flag`) with `--` and short arguments (`-f`) with `-`. I've decided to use the full names regarding `--red` `--blue` and `--green` because the `-r` flag was already in use. If this truly bothers you; you can `-r` from aliasing `--rotate` and alias `--red`, `--green` and `--blue` with `-r`, `-g` and `-b` respectively. If you haven't noticed however, you can specify all the channels by doing `--rgb`.

I'll remove the table from the `--help` section, likely misunderstood it.

I was first slightly confused by the script, and extended `--help` sections tend to help with this, once again. If it is truly bothersome removing/shortening it shouldn't be a problem.

**Comment by onespaceman** [comment]
Merged. Twice. Because someone changed their name. :p

**Comment by muse** [comment]
Haha, there's currently 2? things that I forgot to change but will likely be changed by @sector-f soon.
- Shebang was towards `sh` instead of `bash`.
- Polyfy{1,2,3...} fallback still not working as expected.

**Pull request merged**
